---
title: "wall_dimension_input"
author: "Peter Smallidge"
date: "4/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}

library(tidyverse)
library(skimr)        ## install.packages("skimr")
library(readxl)
#
# ALT plus hypen = <- (within chunk)
# ctrl plus shift plus m = %>% 
# ctrl + ALT + I = insert chunk
# filter rows, select columns
# 

```

### read data from csv file, check variables and data structure

<!-- note to self: 


It is also possible to right-click a file name and import excel
-->

###Input Data and Mutate Variables
```{r, input data mutate variables}

gasline2017_20 <- read_excel("2017-20 Gas Line Slash Dimensions 10-29-2020.xlsx", 
    sheet = "merged", skip=1) %>% 
  mutate_at(vars(harvest, post, year_sampled),
            list(factor)) %>%  #make these variables into factors
  arrange(post, year_sampled)
  
redpine2017_2020 <- read_excel("2017-20 Red Pine Slash Dimensions 11-4-20.xlsx", 
    sheet = "merged", skip = 1) %>% 
  mutate_at(vars(harvest, post, year_sampled),
            list(factor)) #make these variables into factors

boot2018_20200 <- read_excel("2018-20 Boot Slash Wall Dimensions 5-19-20.xlsx", 
    sheet = "merged", skip = 1) %>% 
  mutate_at(vars(harvest, post, year_sampled),
            list(factor)) #make these variables into factors

wedge2018_2020 <- read_excel("2018-20 wedge slash wall dimensions 5-19-2020.xlsx", 
    skip = 1) %>% 
  mutate_at(vars(harvest, post, year_sampled),
            list(factor)) #make these variables into factors


wall_data <- bind_rows(gasline2017_20, redpine2017_2020,
                       boot2018_20200, wedge2018_2020) %>% 
  rename("wall_ht_highest" = "fence_ht_highest", 
         "wall_ht_two" = "fence_ht_two",
         "year" = "year_sampled",
         "month" = "month_sampled") %>% 
  mutate(
    wall_ht_outside_highest = ((-1) * (elev_diff_in_out)) + wall_ht_highest
  ) %>% 
  mutate_at(vars(built),
            list(factor))

wall_data_tidy <- wall_data %>% 
  select(harvest, post, 
         slope_pct, wall_width, wall_ht_outside_highest, wall_ht_outside_two,
         built, year, month, elapsed)


perimeter_summary <- perimeter_area_summary <- read_excel("perimeter_area_summary.xlsx", 
    sheet = "import to r") %>% 
  mutate_at(vars(harvest, map_label, year),
            list(factor)) %>% 
  mutate(
    area_under_wall = perimeter_wall * 22 / 43560,
    perimeter_per_acre = perimeter_harvest / area,
    cost_per_wall_foot = perimeter_wall * 1.5 / area,
  ) %>% 
  rename(cost_per_harvested_acre = cost_per_acre)


```
<!-- 
variables h_dist_post to h_dist_pole are collected
variables fence_ht_highest to wall_ht_outside_two are calculated

fence_ht_highest	= vert dist to highest point - vert dist to post

fence_ht_two	= vert dist two - vert dist post

wall_width	= h dist pole - h dist post

elev_diff_in_out	= sum(v_dist_post, pole_target_ht, extra_ht_pole
                        v_dist_pole_target) * -1

slope_pct	= (elev_diff_in_out / wall_width) * 100

wall_ht_outside_two = elev_diff_in_out + fence_ht_two


-->


###Group Means
```{r, group means}

wall_averages <- wall_data_tidy %>% 
  group_by(harvest, year) %>% 
  summarize(
    n = n(),
    width = mean(wall_width),
    ht_at_two_inch = mean(wall_ht_outside_two),
    ht_highest = mean(wall_ht_outside_highest),
    slope_pct = mean(slope_pct)
  )

write_csv(wall_averages, "wall_average_ht_width.csv")
```



###Looking at Data Patterns
```{r, data patterns ggplot}
wall_data_tidy %>% 
  ggplot(aes(x=year, y=wall_ht_outside_highest, size = wall_width)) +
  geom_point() +
  facet_wrap((~ harvest))

wall_data_tidy %>% 
  ggplot(aes(x=wall_width, y=wall_ht_outside_highest, color = year)) +
  geom_point() +
  facet_wrap((~ harvest))


```


<!-- 
ht_2019_mod <- lm(log(height)~spp*harvest + spp*originx2 + spp*location, data=height_common)

hist(residuals(ht_2019_mod)) #tests for normal distribution
plot(predict(ht_2019_mod), residuals(ht_2019_mod)) #tests heteroscedasticity, thus log

library(emmeans)
emmeans(ht_2019_mod, ~spp+harvest+originx2+location, type="response")
#this calculates the mean and SE for all factor combinations, type=...reverse transformed

emmip(ht_2019_mod, location ~ spp | harvest + originx2, CIs = TRUE)
#plots the data from emmeans to help visualize interactions
# emmip(model name, color ~, xaxis | panel1 + panel2

emmeans(ht_2019_mod, pairwise ~ spp | harvest * location * originx2, type = "response")
#calculates the contrasts
#assess if spp (height) matters as a function of harvest*location*originx2

-->

###Linear Model Wall Width
```{r, linear model width}

wall_width_model <- lm(wall_width~harvest*year, data=wall_data_tidy)

hist(residuals(wall_width_model))
plot(predict(wall_width_model), residuals(wall_width_model))

library(emmeans)
emmeans(wall_width_model, ~harvest+year)

emmip(wall_width_model, harvest~year, CIs=TRUE)  #color~axis, harvest is in color
emmip(wall_width_model, year~harvest, CIs=TRUE)  #color~axis, harvest on x-axis

emmeans(wall_width_model, pairwise ~ year |  harvest * year)

```



###Linear Model Wall Highest
```{r, linear model highest}

wall_highest_model <- lm(wall_ht_outside_highest~harvest*year, data=wall_data_tidy)

hist(residuals(wall_highest_model))
plot(predict(wall_highest_model), residuals(wall_highest_model))

emmeans(wall_highest_model, ~harvest+year)

emmip(wall_highest_model, harvest~year, CIs=TRUE) #color~axis, harvest is in color
emmip(wall_highest_model, year~harvest, CIs=TRUE) #color~axis, harvest on x-axis

emmeans(wall_highest_model, pairwise ~ year | harvest * year)

```



###Linear Model Wall Two Inch
```{r, linear model two inch}

wall_two_model <- lm(log(wall_ht_outside_two)~harvest*year, data=wall_data_tidy)

hist(residuals(wall_two_model))  #there are data outliers that I need to fix
plot(predict(wall_two_model), residuals(wall_two_model))

emmeans(wall_two_model, ~harvest+year, type = "response")

emmip(wall_two_model, harvest~year, CIs=TRUE) #color~axis, harvest is in color
emmip(wall_two_model, year~harvest, CIs=TRUE) #color~axis, harvest on x-axis

emmeans(wall_two_model, pairwise ~ year | harvest * year, type="response")
# sorts by harvest and compares years

emmeans(wall_two_model, pairwise ~ harvest | harvest * year, type="response")
#sorts by year and compares harvests

```




